######################## default configuration ####################
baseURL = "https://nimble-rolypoly-28f489.netlify.app/"
title = "OMEGA"
theme = "omega-hugo"
# google analytics
google_analytics = "G-XXXXXXXXXX" # example : UA-123-45
[markup.goldmark.renderer]
unsafe= true
